- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_packages:
      - { name: go }
      - { name: git }
      - { name: jq }
      - { name: node }
      - { name: peco }
      - { name: tig }
      - { name: tmux }
      - { name: wget }
      - { name: zsh }
    homebrew_cask_packages:
      - { name: atom }
      - { name: sourcetree }
      - { name: webstorm }

  tasks:
    - name: add homebrew tap repository
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install brew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: make directory depends on brew packages
      file: path=brew_info state=directory
    - name: save brew package information
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    - name: install cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed')}}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: make directory that depends on cask packages
      file: path=cask_info state=directory
    - name: save cask package information
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    - name: oh-my-zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh

